// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry, EntryFields, SpaceLink, EnvironmentLink } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IHomePageFields {
  /** Name Logo */
  nameLogo?: Asset | undefined;

  /** Tagline */
  tagline?: string | undefined;

  /** Bio */
  bio?: string | undefined;

  /** Latest Release */
  latestRelease: IRelease;
}

export interface IHomePage extends Entry<IHomePageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: EntryFields.Date;
    updatedAt: EntryFields.Date;
    locale: string;
    contentType: {
      sys: {
        id: "homePage";
        linkType: "ContentType";
        type: "Link";
      };
    };
    revision: number;
    space: { sys: SpaceLink }
    environment: { sys: EnvironmentLink }
  };
}

export interface ILinkFields {
  /** Text */
  text: string;

  /** Path */
  path: string;
}

export interface ILink extends Entry<ILinkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: EntryFields.Date;
    updatedAt: EntryFields.Date;
    locale: string;
    contentType: {
      sys: {
        id: "link";
        linkType: "ContentType";
        type: "Link";
      };
    };
    revision: number;
    space: { sys: SpaceLink }
    environment: { sys: EnvironmentLink }
  };
}

export interface IPrimaryNavigationFields {
  /** Links */
  links?: ILink[] | undefined;
}

export interface IPrimaryNavigation extends Entry<IPrimaryNavigationFields> {
  sys: {
    id: string;
    type: string;
    createdAt: EntryFields.Date;
    updatedAt: EntryFields.Date;
    locale: string;
    contentType: {
      sys: {
        id: "primaryNavigation";
        linkType: "ContentType";
        type: "Link";
      };
    };
    revision: number;
    space: { sys: SpaceLink }
    environment: { sys: EnvironmentLink }
  };
}

export interface IReleaseFields {
  /** Title */
  title: string;

  /** Release Date */
  releaseDate: string;

  /** Cover Art */
  coverArt: Asset;
}

export interface IRelease extends Entry<IReleaseFields> {
  sys: {
    id: string;
    type: string;
    createdAt: EntryFields.Date;
    updatedAt: EntryFields.Date;
    locale: string;
    contentType: {
      sys: {
        id: "release";
        linkType: "ContentType";
        type: "Link";
      };
    };
    revision: number;
    space: { sys: SpaceLink }
    environment: { sys: EnvironmentLink }
  };
}

export type CONTENT_TYPE =
  | "homePage"
  | "link"
  | "primaryNavigation"
  | "release";

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
